// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.3
package com.hacom.order.api.grpc.generate.proto;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string client_id = 2;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 2;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>string client_phone = 3;</code>
   * @return The clientPhone.
   */
  java.lang.String getClientPhone();
  /**
   * <code>string client_phone = 3;</code>
   * @return The bytes for clientPhone.
   */
  com.google.protobuf.ByteString
      getClientPhoneBytes();

  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  java.util.List<com.hacom.order.api.grpc.generate.proto.OrderItem> 
      getItemsList();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  com.hacom.order.api.grpc.generate.proto.OrderItem getItems(int index);
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  java.util.List<? extends com.hacom.order.api.grpc.generate.proto.OrderItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .OrderItem items = 4;</code>
   */
  com.hacom.order.api.grpc.generate.proto.OrderItemOrBuilder getItemsOrBuilder(
      int index);
}
