// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.3
package com.hacom.order.api.grpc.generate.proto;

public interface OrderItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productId = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string productId = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();
}
