// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.3
package com.hacom.order.api.grpc.generate.proto;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"d\n\014OrderRequest\022\020\n\010order_i" +
      "d\030\001 \001(\t\022\021\n\tclient_id\030\002 \001(\t\022\024\n\014client_pho" +
      "ne\030\003 \001(\t\022\031\n\005items\030\004 \003(\0132\n.OrderItem\"1\n\rO" +
      "rderResponse\022\020\n\010order_id\030\001 \001(\t\022\016\n\006status" +
      "\030\002 \001(\t\"?\n\tOrderItem\022\021\n\tproductId\030\001 \001(\t\022\020" +
      "\n\010quantity\030\002 \001(\005\022\r\n\005price\030\003 \001(\0012<\n\014Order" +
      "Service\022,\n\013CreateOrder\022\r.OrderRequest\032\016." +
      "OrderResponseB0\n com.hacom.order.api.grp" +
      "c.serviceB\nOrderProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "OrderId", "ClientId", "ClientPhone", "Items", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "Status", });
    internal_static_OrderItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
